jdbc.enable=false
jdbc.scan-packages=com.github,com.hahah

servlet.enable=true
servlet.version=3
servlet.scanPackages=com.github

log.level=info

# 方法耗时链路监控
timing.enable=true
timing.packages=com.lawrence.test.javassist._03
timing.exclude-packages=